project:
  output-dir: _slides
  render:
    - index.qmd
    - syllabus.qmd
    - slides.qmd
    - assignments.qmd
    - about.qmd
    - 01-week1-slides-code.qmd
    

website:
  title: "Data Cleaning and Management (FQ23)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: slides.qmd
        text: Slides
      - href: assignments.qmd
        text: Problem Sets
      - about.qmd
      
  sidebar:
    - title: "Slides"
      style: "docked"
      background: light
      contents:
        - 01-week1-slides-code.qmd

format:
  revealjs:
    incremental: true
    code-tools: true
    code-copy: true
    code-line-numbers: true
    code-link: true
    preview-links: true
    slide-number: true
    self-contained: true
    css: custom.css
    theme: psc290
    highlight-style: atom-one-dark
    margin-left: "0"
    margin-right: "0"
    # width: 1400
    # height: 900
    footer: "PSC 290 - Data Cleaning and Management"
    logo: "https://github.com/emoriebeck/psc290-data-viz-2022/raw/main/01-week1-intro/02-code/02-images/ucdavis_logo_blue.png"

editor: visual

