---
title: "Data Cleaning and Management (Fall 2023)"
---

## **Course Description**

In graduate education, training on research (and statistical) methods and conceptual frameworks far outpaces training on key technical skills that underpin all research, empirical or otherwise. On average, researchers spend about 80% of their (analytic) time on data cleaning, but we spend comparatively little teaching those skills. This course aims to fill that gap by helping researchers to (1) build their reproducible research workflow and (2) improve their data cleaning and general statistical programming skills. To that end, each session will be split to address each of these goals, with the beginning of class focused on conceptual ideas about best practices in building a workflow and the latter half focused on technical training on programming and cleaning data in R. This course will be set up as a \"bring your own data\" course to allow students to anticipate specific challenges that face different types of research. 

This course is not a \"pure\" data science (i.e. we won\'t be working with databases, etc.) because it focuses on the skills and tools most common within the social sciences. Science is a collaborative enterprise, and these tools are widely used among many social scientists, which promotes an open, equitable workflow by using tools available and most commonly used by the majority of our peers. 

## **Navigating This Site:** 

1\. Weekly assignments are under **Assignments**. These are due at 12:01 AM on the day of class. 

2\. Reading list (and links) and links to workshop slides are under **Schedule** and on Canvas. I recommend bookmark this site to allow you access to all materials in perpetuity.

3\. Final Project information and class participation are under Assignments**.** Be sure to familiarize yourself with due dates for the final projects. More details will be provided on the final project in the coming weeks.

4\. The most updated version of the syllabus will be on the Syllabus page and can be downloaded there as well.

 
