project:
  type: website

website:
  title: "Data Cleaning and Management (FQ23)"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - sidebar:slides
      - text: "Schedule"
        file: schedule.qmd
      - sidebar:assignments
      - about.qmd
      
  sidebar:
    - id: slides
      title: "Slides"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - 01-week1-slides.qmd
        - 01-week1-workbook.qmd
        # - 02-week2.qmd
        
    - id: assignments
      title: "Problem Sets"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - ps1-week1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

