---
title: "Final Project Paper Rubric"
subtitle: "PSC290 - Data Cleaning and Management, Fall 2023"
author: "Emorie D Beck"
institution: "University of California, Davis"
format: html
---

-   Due at 11:59 PM PST on December 15, 2022 on Canvas

| Section / Description                                                                                                                                                                                                                                                                                                                                                                                                              | Points        |
|-------------------------------------------------------|-----------------|
| **Short Background**: What is the project you are working on? Basically, this section should give me enough information to understand the research project (if applicable) or 1-2 paragraphs is sufficient in most cases.                                                                                                                                                                                                          | 5 points      |
| **Motivation**: Clearly state why you are creating the product. What problems does it address? How will you integrate it into your workflow? How will it change your workflow, etc. There is no minimum of maximum length, but my guess is 1-2 paragraphs.                                                                                                                                                                         | 5 points      |
| **Approach**: Short description of how you went about creating your product. Describe what tools you used, how you went about creating the product (e.g., built a shell and then built the rest out from there). There is no minimum of maximum length, but my guess is no less than 2-3 paragraphs.                                                                                                                               | 10 points     |
| **Reflection**: Reflect on what you learned in this project / class. What course concepts did you draw on? What barriers did you have to overcome to complete the project? If you were to start over, would you do it the same way again or take a different strategy? These are just some examples of questions to consider in reflecting on your project. There is no minimum of maximum length, but my guess is 2-3 paragraphs. | 5 points      |
| **Total**                                                                                                                                                                                                                                                                                                                                                                                                                          | **25 points** |
