---
title: "Schedule"
---

Course Schedule

Note: Course schedule is subject to change without notice.

+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **Day** | **Date**   | **Topic**                                                                                                                                                                                                                                                                                                        | **Due Today**     |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
|         |            | [**First Day of Classes September 27**]{.underline}                                                                                                                                                                                                                                                              |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **1**   | 10/02/2023 | [*Lecture*]{.underline}: Basics of Workflow                                                                                                                                                                                                                                                                      |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Introduction to R & Workflow Basics; Quarto                                                                                                                                                                                                                                            |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       r4ds: Ch. [3](https://r4ds.hadley.nz/workflow-basics), [5](https://r4ds.hadley.nz/workflow-style), [7](https://r4ds.hadley.nz/workflow-scripts), [29](https://r4ds.hadley.nz/quarto)                                                                                                                     |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/yk8CP9_vwEj1o1LTZNXBxQdigb11vhKEShKMRmlmAJ7dBOAdWRJI4b-V10TItzVM.WPaSYWimDpt47FB1?startTime=1696281202000)                                                                                                                                                    |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **2**   | 10/09/2023 | [*Lecture*]{.underline}: Reproducibility and Workflow Values                                                                                                                                                                                                                                                     | Problem Set 1 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Data Transformation: Introduction to **dplyr**                                                                                                                                                                                                                                         |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       r4ds: Ch. [4](https://r4ds.hadley.nz/data-transform)                                                                                                                                                                                                                                                     |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/wmYwnrsrxcRSfeDysh5SXkAf1iTdJkRF-UMK1fzyvXr38F_Tk1t0znfAU6TUitZW.nMXgOZjYNXVRzmjT)                                                                                                                                                                            |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **3**   | 10/16/2023 | [*Lecture*]{.underline}: Understanding and Assessing Data Quality                                                                                                                                                                                                                                                | Problem Set 2 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Reshaping and Joining: Introduction to **tidyr**                                                                                                                                                                                                                                       |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       r4ds: Ch. [6](https://r4ds.hadley.nz/data-tidy)                                                                                                                                                                                                                                                          |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/I3oITDflRnmTM8tdlHHq7mTxUyDjojKXNsC2OCGijO-fPn-p9GUsYEdMILPnAwfk.sTATX8DQpGiQHoNe)                                                                                                                                                                            |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **4**   | 10/23/2023 | [*Lecture*]{.underline}: Documenting Data and Procedures                                                                                                                                                                                                                                                         | Problem Set 3 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Using Codebooks to Aid Data Import                                                                                                                                                                                                                                                     |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       r4ds: Ch. [8](https://r4ds.hadley.nz/data-import), [21](https://r4ds.hadley.nz/spreadsheets), [24](https://r4ds.hadley.nz/rectangling)                                                                                                                                                                   |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | Zoom Recording in 2 parts due to technical issues [(Part 1](https://ucdavis.zoom.us/rec/share/2VC5oIcfKQ5-rV_4rGO8iR4JUXj5ckYJqThEJ7FLIz_i8nl7ix_21zgalK79SsIm.aFB88Aybr6NADZJN); [Part 2)](https://ucdavis.zoom.us/rec/share/I5qAg3RoMCSXf_5nU4o9jLnvyZQNxfDaYwXPfGEUKeNYiPDDPRYyVoSd5e8jTe-8.THFrq6F2wLjg_HBf) |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **5**   | 10/30/2023 | [*Lecture*]{.underline}: Functions                                                                                                                                                                                                                                                                               | Problem Set 4 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Iteration: Introduction to **purrr**                                                                                                                                                                                                                                                   |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       r4ds: Ch. [26](https://r4ds.hadley.nz/functions), [27](https://r4ds.hadley.nz/iteration)                                                                                                                                                                                                                 |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/FDh53Qzkh6P77fbZvLktO28_sHef_88ngcC1x3EFzIM1P-VTOlzfVHWElwN9s0kY.whd7Xz8g1fkrd60c)                                                                                                                                                                            |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **6**   | 11/06/2023 | [*Lecture*]{.underline}: Review -- Putting the Pieces of Your Workflow Together                                                                                                                                                                                                                                  | Problem Set 5 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Review -- tidyverse: Using codebooks, functions, and iteration within a tidyverse framework (a series of in-class activities)                                                                                                                                                          |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}: None                                                                                                                                                                                                                                                                                   |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/ZJNGbyjV4aA36t9eaVTonHj7YjeGSBbfqSXeI5IX6RSWcM67z_IG5yVGSagr-gg.iDKecP36I6jAWsd7)                                                                                                                                                                             |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **7**   | 11/13/2023 | [*Lecture*]{.underline}: Data Structures in R                                                                                                                                                                                                                                                                    | Problem Set 6 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Data Transformation: Dates, Strings, regex, and Other Tricky Classes                                                                                                                                                                                                                   |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       r4ds: Ch. [13](https://r4ds.hadley.nz/logicals)-[19](https://r4ds.hadley.nz/missing-values)                                                                                                                                                                                                              |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/GHDlKX9K6yEm4DYlWS6xzTxQ97VQ9HeyFL6YT_2CwOsw7CzKfpVhDODK5H3Z4lbm.Ye1Ab9hzsQV00iB2)                                                                                                                                                                            |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **8**   | 11/20/2023 | [*Lecture*]{.underline}: GitHub and Versioning                                                                                                                                                                                                                                                                   | Problem Set 7 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: (Functional) Tables & Figures                                                                                                                                                                                                                                                          | **PROPOSALS DUE** |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       TBD                                                                                                                                                                                                                                                                                                      |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/EI0rGnhUieNWvByozy3-c4MGN1wWWBxgwFC7Zv39Ijgpqx2SKF12iLU5-kVTVZdX.pt4oCaHEHnSjNNKu)                                                                                                                                                                            |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
|         |            | [Thanksgiving Break]{.underline}                                                                                                                                                                                                                                                                                 |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **9**   | 11/27/2023 | [*Lecture*]{.underline}: Using R resources efficiently                                                                                                                                                                                                                                                           | Problem Set 8 Due |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Workshop*]{.underline}: Parallelization: Introduction to **future** and **furrr**                                                                                                                                                                                                                              |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [*Readings*]{.underline}:                                                                                                                                                                                                                                                                                        |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | -       <https://dcgerard.github.io/advancedr/09_future.html>                                                                                                                                                                                                                                                    |                   |
|         |            |                                                                                                                                                                                                                                                                                                                  |                   |
|         |            | [Zoom Recording](https://ucdavis.zoom.us/rec/share/H3rdtuBa1u5LUP0s1hP3Oh6YkvO42zq5dsGmMP5eAKn7FAbjxRNoY9wOvOBnV_S5.yi-Rn8CNhOJFyVA8)                                                                                                                                                                            |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| **10**  | 12/04/2023 | Review + Code hacks                                                                                                                                                                                                                                                                                              |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
|         | 12/15/2023 | Final Project Due Date                                                                                                                                                                                                                                                                                           |                   |
+---------+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
